server.port=${PORT:8080}
spring.application.name=bfhl-api

# Disable unnecessary auto-configurations
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Jackson
spring.jackson.default-property-inclusion=non_null
